### ISSUE TITLE
First peer to peer code review

### ISSUE THREAD

**Issue by MesakDuduCoder** [MesakDuduCoder/Portfolio-mobile#3]
This is the first code review of the morning team session. (28/02/2023)

**Comment by Christelle-12** [comment]
Hello, You have really done a great job!!, your codes are good and clean nothing else to correct.

**Comment by yawsamcode** [comment]
Good job @MesakDuduCoder your code was clean I must say. keep it up. 👍👍👍👍

**Comment by MesakDuduCoder** [comment]
Thank you everyone for much for the positive feedback and review.

**Comment by Jawad-Nazari** [comment]
> This is the first code review of the morning team session. (28/02/2023)

Well done @MesakDuduCoder  ,
Nice code, as I see everything is fine and there is nothing to fix.
